#=============================================================
# $Id: Makefile,v 1.1 2006/01/25 04:32:39 rocky Exp $
#=============================================================
# Whatever it is you want to do, it should be handled by the 
# by the main (parent) Makefile. So reissue make from there.
all %:
	$(MAKE) -C .. $@
